export const CONSTITUENCIES = [
    { id: 1, name: 'Changamwe', countyId: 1 }, { id: 2, name: 'Jomvu', countyId: 1 },
    { id: 3, name: 'Kisauni', countyId: 1 }, { id: 4, name: 'Likoni', countyId: 1 },
    { id: 5, name: 'Mvita', countyId: 1 }, { id: 6, name: 'Nyali', countyId: 1 },
    { id: 7, name: 'Kinango', countyId: 2 }, { id: 8, name: 'Lunga Lunga', countyId: 2 },
    { id: 9, name: 'Msambweni', countyId: 2 }, { id: 10, name: 'Matuga', countyId: 2 },
    { id: 11, name: 'Kilifi North', countyId: 3 }, { id: 12, name: 'Kilifi South', countyId: 3 },
    { id: 13, name: 'Kaloleni', countyId: 3 }, { id: 14, name: 'Ganze', countyId: 3 },
    { id: 15, name: 'Magarini', countyId: 3 }, { id: 16, name: 'Rabai', countyId: 3 },
    { id: 17, name: 'Malindi', countyId: 3 }, { id: 18, name: 'Garsen', countyId: 4 },
    { id: 19, name: 'Galole', countyId: 4 }, { id: 20, name: 'Bura', countyId: 4 },
    { id: 21, name: 'Lamu East', countyId: 5 }, { id: 22, name: 'Lamu West', countyId: 5 },
    { id: 23, name: 'Taveta', countyId: 6 }, { id: 24, name: 'Wundanyi', countyId: 6 },
    { id: 25, name: 'Mwatate', countyId: 6 }, { id: 26, name: 'Voi', countyId: 6 },
    { id: 27, name: 'Garissa Township', countyId: 7 }, { id: 28, name: 'Balambala', countyId: 7 },
    { id: 29, name: 'Dadaab', countyId: 7 }, { id: 30, name: 'Fafi', countyId: 7 },
    { id: 31, name: 'Ijara', countyId: 7 }, { id: 32, name: 'Lagdera', countyId: 7 },
    { id: 33, name: 'Wajir East', countyId: 8 }, { id: 34, name: 'Wajir North', countyId: 8 },
    { id: 35, name: 'Wajir South', countyId: 8 }, { id: 36, name: 'Wajir West', countyId: 8 },
    { id: 37, name: 'Tarbaj', countyId: 8 }, { id: 38, name: 'Eldas', countyId: 8 },
    { id: 39, name: 'Mandera West', countyId: 9 }, { id: 40, name: 'Banissa', countyId: 9 },
    { id: 41, name: 'Mandera North', countyId: 9 }, { id: 42, name: 'Mandera South', countyId: 9 },
    { id: 43, name: 'Mandera East', countyId: 9 }, { id: 44, name: 'Lafey', countyId: 9 },
    { id: 45, name: 'Laisamis', countyId: 10 }, { id: 46, name: 'North Horr', countyId: 10 },
    { id: 47, name: 'Saku', countyId: 10 }, { id: 48, name: 'Moyale', countyId: 10 },
    { id: 49, name: 'Isiolo North', countyId: 11 }, { id: 50, name: 'Isiolo South', countyId: 11 },
    { id: 51, name: 'Buuri', countyId: 12 }, { id: 52, name: 'Central Imenti', countyId: 12 },
    { id: 53, name: 'Igembe Central', countyId: 12 }, { id: 54, name: 'Igembe South', countyId: 12 },
    { id: 55, name: 'Igembe North', countyId: 12 }, { id: 56, name: 'Tigania West', countyId: 12 },
    { id: 57, name: 'Tigania East', countyId: 12 }, { id: 58, name: 'Imenti North', countyId: 12 },
    { id: 59, name: 'Imenti South', countyId: 12 }, { id: 60, name: 'Tharaka', countyId: 13 },
    { id: 61, name: "Chuka/Igambang'ombe", countyId: 13 }, { id: 62, name: 'Maara', countyId: 13 },
    { id: 63, name: 'Manyatta', countyId: 14 }, { id: 64, name: 'Runyenjes', countyId: 14 },
    { id: 65, name: 'Mbeere North', countyId: 14 }, { id: 66, name: 'Mbeere South', countyId: 14 },
    { id: 67, name: 'Kitui West', countyId: 15 }, { id: 68, name: 'Kitui Central', countyId: 15 },
    { id: 69, name: 'Kitui Rural', countyId: 15 }, { id: 70, name: 'Kitui South', countyId: 15 },
    { id: 71, name: 'Kitui East', countyId: 15 }, { id: 72, name: 'Mwingi North', countyId: 15 },
    { id: 73, name: 'Mwingi West', countyId: 15 }, { id: 74, name: 'Mwingi Central', countyId: 15 },
    { id: 75, name: 'Masinga', countyId: 16 }, { id: 76, name: 'Yatta', countyId: 16 },
    { id: 77, name: 'Matungulu', countyId: 16 }, { id: 78, name: 'Kangundo', countyId: 16 },
    { id: 79, name: 'Mwala', countyId: 16 }, { id: 80, name: 'Kathiani', countyId: 16 },
    { id: 81, name: 'Machakos Town', countyId: 16 }, { id: 82, name: 'Mavoko', countyId: 16 },
    { id: 83, name: 'Mbooni', countyId: 17 }, { id: 84, name: 'Kaiti', countyId: 17 },
    { id: 85, name: 'Makueni', countyId: 17 }, { id: 86, name: 'Kilome', countyId: 17 },
    { id: 87, name: 'Kibwezi East', countyId: 17 }, { id: 88, name: 'Kibwezi West', countyId: 17 },
    { id: 89, name: 'Kinangop', countyId: 18 }, { id: 90, name: 'Kipipiri', countyId: 18 },
    { id: 91, name: 'Ol Joro Orok', countyId: 18 }, { id: 92, name: 'Ndaragwa', countyId: 18 },
    { id: 93, name: 'Ol Kalou', countyId: 18 }, { id: 94, name: 'Mathira', countyId: 19 },
    { id: 95, name: 'Othaya', countyId: 19 }, { id: 96, name: 'Tetu', countyId: 19 },
    { id: 97, name: 'Mukurweini', countyId: 19 }, { id: 98, name: 'Nyeri Town', countyId: 19 },
    { id: 99, name: 'Kieni', countyId: 19 }, { id: 100, name: 'Kirinyaga Central', countyId: 20 },
    { id: 101, name: 'Mwea', countyId: 20 }, { id: 102, name: 'Gichugu', countyId: 20 },
    { id: 103, name: 'Ndia', countyId: 20 }, { id: 104, name: 'Gatanga', countyId: 21 },
    { id: 105, name: 'Kandara', countyId: 21 }, { id: 106, name: 'Kigumo', countyId: 21 },
    { id: 107, name: 'Mathioya', countyId: 21 }, { id: 108, name: 'Kiharu', countyId: 21 },
    { id: 109, name: 'Kangema', countyId: 21 }, { id: 110, name: 'Maragwa', countyId: 21 },
    { id: 111, name: 'Gatundu North', countyId: 22 }, { id: 112, name: 'Gatundu South', countyId: 22 },
    { id: 113, name: 'Githunguri', countyId: 22 }, { id: 114, name: 'Juja', countyId: 22 },
    { id: 115, name: 'Kabete', countyId: 22 }, { id: 116, name: 'Kiambaa', countyId: 22 },
    { id: 117, name: 'Kiambu', countyId: 22 }, { id: 118, name: 'Limuru', countyId: 22 },
    { id: 119, name: 'Kikuyu', countyId: 22 }, { id: 120, name: 'Lari', countyId: 22 },
    { id: 121, name: 'Ruiru', countyId: 22 }, { id: 122, name: 'Thika Town', countyId: 22 },
    { id: 123, name: 'Turkana Central', countyId: 23 }, { id: 124, name: 'Turkana East', countyId: 23 },
    { id: 125, name: 'Turkana North', countyId: 23 }, { id: 126, name: 'Turkana South', countyId: 23 },
    { id: 127, name: 'Turkana West', countyId: 23 }, { id: 128, name: 'Loima', countyId: 23 },
    { id: 129, name: 'Kapenguria', countyId: 24 }, { id: 130, name: 'Sigor', countyId: 24 },
    { id: 131, name: 'Kacheliba', countyId: 24 }, { id: 132, name: 'Pokot South', countyId: 24 },
    { id: 133, name: 'Samburu East', countyId: 25 }, { id: 134, name: 'Samburu North', countyId: 25 },
    { id: 135, name: 'Samburu West', countyId: 25 }, { id: 136, name: "Cherang'any", countyId: 26 },
    { id: 137, name: 'Kwanza', countyId: 26 }, { id: 138, name: 'Endebess', countyId: 26 },
    { id: 139, name: 'Saboti', countyId: 26 }, { id: 140, name: 'Kiminini', countyId: 26 },
    { id: 141, name: 'Ainabkoi', countyId: 27 }, { id: 142, name: 'Kapseret', countyId: 27 },
    { id: 143, name: 'Kesses', countyId: 27 }, { id: 144, name: 'Moiben', countyId: 27 },
    { id: 145, name: 'Soy', countyId: 27 }, { id: 146, name: 'Turbo', countyId: 27 },
    { id: 147, name: 'Keiyo North', countyId: 28 }, { id: 148, name: 'Keiyo South', countyId: 28 },
    { id: 149, name: 'Marakwet East', countyId: 28 }, { id: 150, name: 'Marakwet West', countyId: 28 },
    { id: 151, name: 'Aldai', countyId: 29 }, { id: 152, name: 'Chesumei', countyId: 29 },
    { id: 153, name: 'Emgwen', countyId: 29 }, { id: 154, name: 'Mosop', countyId: 29 },
    { id: 155, name: 'Nandi Hills', countyId: 29 }, { id: 156, name: 'Tinderet', countyId: 29 },
    { id: 157, name: 'Baringo Central', countyId: 30 }, { id: 158, name: 'Baringo North', countyId: 30 },
    { id: 159, name: 'Baringo South', countyId: 30 }, { id: 160, name: 'Eldama Ravine', countyId: 30 },
    { id: 161, name: 'Mogotio', countyId: 30 }, { id: 162, name: 'Tiaty', countyId: 30 },
    { id: 163, name: 'Laikipia North', countyId: 31 }, { id: 164, name: 'Laikipia East', countyId: 31 },
    { id: 165, name: 'Laikipia West', countyId: 31 }, { id: 166, name: 'Nakuru Town East', countyId: 32 },
    { id: 167, name: 'Nakuru Town West', countyId: 32 }, { id: 168, name: 'Njoro', countyId: 32 },
    { id: 169, name: 'Molo', countyId: 32 }, { id: 170, name: 'Gilgil', countyId: 32 },
    { id: 171, name: 'Naivasha', countyId: 32 }, { id: 172, name: 'Kuresoi North', countyId: 32 },
    { id: 173, name: 'Kuresoi South', countyId: 32 }, { id: 174, name: 'Bahati', countyId: 32 },
    { id: 175, name: 'Rongai', countyId: 32 }, { id: 176, name: 'Subukia', countyId: 32 },
    { id: 177, name: 'Narok North', countyId: 33 }, { id: 178, name: 'Narok South', countyId: 33 },
    { id: 179, name: 'Narok East', countyId: 33 }, { id: 180, name: 'Narok West', countyId: 33 },
    { id: 181, name: 'Kilgoris', countyId: 33 }, { id: 182, name: 'Emurua Dikirr', countyId: 33 },
    { id: 183, name: 'Kajiado Central', countyId: 34 }, { id: 184, name: 'Kajiado East', countyId: 34 },
    { id: 185, name: 'Kajiado North', countyId: 34 }, { id: 186, name: 'Kajiado West', countyId: 34 },
    { id: 187, name: 'Kajiado South', countyId: 34 }, { id: 188, name: 'Ainamoi', countyId: 35 },
    { id: 189, name: 'Belgut', countyId: 35 }, { id: 190, name: 'Bureti', countyId: 35 },
    { id: 191, name: 'Kipkelion East', countyId: 35 }, { id: 192, name: 'Kipkelion West', countyId: 35 },
    { id: 193, name: 'Soin Sigowet', countyId: 35 }, { id: 194, name: 'Sotik', countyId: 36 },
    { id: 195, name: 'Bomet Central', countyId: 36 }, { id: 196, name: 'Bomet East', countyId: 36 },
    { id: 197, name: 'Chepalungu', countyId: 36 }, { id: 198, name: 'Konoin', countyId: 36 },
    { id: 199, name: 'Butere', countyId: 37 }, { id: 200, name: 'Ikolomani', countyId: 37 },
    { id: 201, name: 'Khwisero', countyId: 37 }, { id: 202, name: 'Lurambi', countyId: 37 },
    { id: 203, name: 'Likuyani', countyId: 37 }, { id: 204, name: 'Malava', countyId: 37 },
    { id: 205, name: 'Matungu', countyId: 37 }, { id: 206, name: 'Mumias East', countyId: 37 },
    { id: 207, name: 'Mumias West', countyId: 37 }, { id: 208, name: 'Navakholo', countyId: 37 },
    { id: 209, name: 'Lugari', countyId: 37 }, { id: 210, name: 'Shinyalu', countyId: 37 },
    { id: 211, name: 'Emuhaya', countyId: 38 }, { id: 212, name: 'Hamisi', countyId: 38 },
    { id: 213, name: 'Sabatia', countyId: 38 }, { id: 214, name: 'Vihiga', countyId: 38 },
    { id: 215, name: 'Luanda', countyId: 38 }, { id: 216, name: 'Bumula', countyId: 39 },
    { id: 217, name: 'Kanduyi', countyId: 39 }, { id: 218, name: 'Webuye East', countyId: 39 },
    { id: 219, name: 'Webuye West', countyId: 39 }, { id: 220, name: 'Mt. Elgon', countyId: 39 },
    { id: 221, name: 'Sirisia', countyId: 39 }, { id: 222, name: 'Tongaren', countyId: 39 },
    { id: 223, name: 'Kabuchai', countyId: 39 }, { id: 224, name: 'Kimilili', countyId: 39 },
    { id: 225, name: 'Teso North', countyId: 40 }, { id: 226, name: 'Teso South', countyId: 40 },
    { id: 227, name: 'Nambale', countyId: 40 }, { id: 228, name: 'Matayos', countyId: 40 },
    { id: 229, name: 'Butula', countyId: 40 }, { id: 230, name: 'Funyula', countyId: 40 },
    { id: 231, name: 'Alego Usonga', countyId: 41 }, { id: 232, name: 'Gem', countyId: 41 },
    { id: 233, name: 'Bondo', countyId: 41 }, { id: 234, name: 'Rarieda', countyId: 41 },
    { id: 235, name: 'Ugenya', countyId: 41 }, { id: 236, name: 'Ugunja', countyId: 41 },
    { id: 237, name: 'Kisumu Central', countyId: 42 }, { id: 238, name: 'Kisumu East', countyId: 42 },
    { id: 239, name: 'Kisumu West', countyId: 42 }, { id: 240, name: 'Seme', countyId: 42 },
    { id: 241, name: 'Nyando', countyId: 42 }, { id: 242, name: 'Muhoroni', countyId: 42 },
    { id: 243, name: 'Nyakach', countyId: 42 }, { id: 244, name: 'Homa Bay Town', countyId: 43 },
    { id: 245, name: 'Kabondo Kasipul', countyId: 43 }, { id: 246, name: 'Karachuonyo', countyId: 43 },
    { id: 247, name: 'Kasipul', countyId: 43 }, { id: 248, name: 'Ndhiwa', countyId: 43 },
    { id: 249, name: 'Rangwe', countyId: 43 }, { id: 250, name: 'Suba North', countyId: 43 },
    { id: 251, name: 'Suba South', countyId: 43 }, { id: 252, name: 'Rongo', countyId: 44 },
    { id: 253, name: 'Awendo', countyId: 44 }, { id: 254, name: 'Suna East', countyId: 44 },
    { id: 255, name: 'Suna West', countyId: 44 }, { id: 256, name: 'Uriri', countyId: 44 },
    { id: 257, name: 'Nyatike', countyId: 44 }, { id: 258, name: 'Kuria East', countyId: 44 },
    { id: 259, name: 'Kuria West', countyId: 44 }, { id: 260, name: 'Kitutu Chache North', countyId: 45 },
    { id: 261, name: 'Kitutu Chache South', countyId: 45 }, { id: 262, name: 'Nyaribari Masaba', countyId: 45 },
    { id: 263, name: 'Nyaribari Chache', countyId: 45 }, { id: 264, name: 'Bomachoge Borabu', countyId: 45 },
    { id: 265, name: 'Bomachoge Chache', countyId: 45 }, { id: 266, name: 'Bobasi', countyId: 45 },
    { id: 267, name: 'South Mugirango', countyId: 45 }, { id: 268, name: 'Bonchari', countyId: 45 },
    { id: 269, name: 'Borabu', countyId: 46 }, { id: 270, name: 'Kitutu Masaba', countyId: 46 },
    { id: 271, name: 'West Mugirango', countyId: 46 }, { id: 272, name: 'North Mugirango', countyId: 46 },
    { id: 273, name: 'Westlands', countyId: 47 }, { id: 274, name: 'Dagoretti North', countyId: 47 },
    { id: 275, name: 'Dagoretti South', countyId: 47 }, { id: 276, name: "Lang'ata", countyId: 47 },
    { id: 277, name: 'Kibra', countyId: 47 }, { id: 278, name: 'Roysambu', countyId: 47 },
    { id: 279, name: 'Kasarani', countyId: 47 }, { id: 280, name: 'Ruaraka', countyId: 47 },
    { id: 281, name: 'Embakasi South', countyId: 47 }, { id: 282, name: 'Embakasi North', countyId: 47 },
    { id: 283, name: 'Embakasi Central', countyId: 47 }, { id: 284, name: 'Embakasi East', countyId: 47 },
    { id: 285, name: 'Embakasi West', countyId: 47 }, { id: 286, name: 'Makadara', countyId: 47 },
    { id: 287, name: 'Kamukunji', countyId: 47 }, { id: 288, name: 'Starehe', countyId: 47 },
    { id: 289, name: 'Mathare', countyId: 47 }, { id: 290, name: 'Budalangi', countyId: 40 }
];
